apiVersion: v1
kind: Service
metadata:
  name: ianvs-dashboard
  namespace: ianvs-benchmark
  labels:
    app: ianvs
    component: dashboard
spec:
  type: NodePort
  selector:
    app: ianvs
    component: cloud-master
  ports:
  - name: http
    port: 8501
    targetPort: 8501
    nodePort: 30850
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: ianvs-cloud-master
  namespace: ianvs-benchmark
  labels:
    app: ianvs
    component: cloud-master
spec:
  type: ClusterIP
  selector:
    app: ianvs
    component: cloud-master
  ports:
  - name: grpc
    port: 9000
    targetPort: 9000
    protocol: TCP
